apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 50000
      name: "slave"
      targetPort: 50000
