apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0     
      containers:
      - name: jenkins
        image: jenkins/jenkins:alpine
        env:
          - name: JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "0.5"
          limits:
            memory: "4096Mi"
            cpu: "0.8"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 50000
          name: jnlp-port
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home                              
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
                
         
