apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 9082
      name: "http"
      nodePort: 30000
      targetPort: 8080
